# https://sleele.com/2020/03/16/%E9%AB%98%E9%98%B6%E6%95%99%E7%A8%8B-%E8%BF%BD%E5%89%A7%E5%85%A8%E6%B5%81%E7%A8%8B%E8%87%AA%E5%8A%A8%E5%8C%96/
version: "3.9"
 
services:
  # qbittorrent，推荐使用 host 网络模式，性能更好，少一层nat
  # 并且后面 下载器IP地址填写简单，填写 172.17.0.1 即可
  # 注意：所有的UID，GID，要根据你的实际情况填写，不懂就都填写 0
  # volumes 下的存储位置，请根据的实际情况修改
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume2/存储池2/影视:/影视
    network_mode: host
    restart: unless-stopped   
    
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped   
 
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped
 
  # 需要两个 sonarr 的同学，再添加一个sonarr容器即可，记得更改 名字和端口映射
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped   
 
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1026 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - TZ=Asia/Shanghai
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /volume1/docker/emby:/config
      - /volume2/存储池2/影视:/影视
    ports:
      - 8096:8096 # HTTP port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: unless-stopped
 
  # 网络方面，网络访问不通畅的可以用小猫咪，懂的用，不懂的请勿操作
  # clash:
  #   image: dreamacro/clash-premium
  #   container_name: clash
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - /volume1/docker/clash:/root/.config/clash
