version: '3.9'

services:
  odoo:
    image: odoo:12.0
    container_name: odoo
    restart: always
    ports:
      - "8069:8069"
    networks:
      - postgres
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./data/data:/var/lib/odoo
      - ./data/config:/etc/odoo
      - ./data/addons:/mnt/extra-addons

networks:
    postgres:
        external: true
    odoo:
        external: true
