version: "3.9"

services:
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwardenrs
    restart: always
    ports:
        - "127.0.0.1:8088:80" #将宿主机8088端口映射到docker的80端口
        - "127.0.0.1:3012:3012"
    volumes:
      - ./bw-data:/data
    environment:
      WEBSOCKET_ENABLED: "true" #是否开启WebSocket
      SIGNUPS_ALLOWED: "false"   #是否开启注册，先设置为true,搭建完毕自己注册后再改为false
      WEB_VAULT_ENABLED: "true" #是否开启Web客户端，设为true
      #ADMIN_TOKEN: ""   #后台登陆密码，这个一般就不建议开启了，自用基本上也不需要直接注释或者删除都行，当前是没启用，如需启用去掉ADMIN_TOKEN前面的 # ，并生成安全密码