version: '3.9'

services:
  aria2:
    image: ${ARIA2_IMAGE}
    container_name: aria2
    volumes:
      - ./downloads:/downloads
    expose:
      - 6800
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true
