version: "3.9"

services:
  nas-tools:
    # image: jxxghp/nas-tools:latest
    image: sungamma/nas-tools:2.9.1
    container_name: nas-tools
    restart: always
    ports:
      - 3003:3000 # 默认的webui控制端口
    volumes:
      - ../../../custom-apps-data/nas-tools/config:/config # 冒号左边请修改为你想保存配置的路径
      - /share/Download:/Download
      - /share/Media:/media # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
    environment: 
      - PUID=0 # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0 # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=022 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=false
      #- REPO_URL=https://ghproxy.com/https://github.com/jxxghp/nas-tools.git  
      # 当你访问github网络很差时，可以考虑解释本行注释
    network_mode: bridge
    hostname: nas-tools

