version: '3.9'

services:
  wordpress:
    depends_on:
      - memcached
    image: 'wordpress:latest'
    ports:
      - '80:80'
    expose:
      - 80
    restart: always
    volumes:
      - './wordpress:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: td_
  wp-cli:
    image: pattonwebz/docker-wpcli
    links:
      - 'db:mysql'
    entrypoint: wp
    command: '--info'
  memcached:
    image: 'amd64/memcached:1.5'
    
volumes:
  db_data: null
  wordpress: null
