version: '3.9'

services:
    mongodb:
        image: mongo
        container_name: mongo
        hostname: mongo
        restart: always
        ports:
            - "27017:27017"
        networks:
            - test

networks:
    test:
        driver: bridge
