version: "3.9"

services:
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
