version: "3.7"

services:
  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home \
