version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ../../../custom-apps-data/jackett/config:/config
      - ../../../custom-apps-data/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    network_mode: bridge
    hostname: jackett
