version: '3.9'

services:
    whoami:
        image: traefik/whoami
        container_name: whoami
        # networks:
        #     - traefik
        #     # - docker_bridge
        #     - bridge
        network_mode: bridge
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"

            - "traefik.http.routers.whoami.entrypoints=http"
            - "traefik.http.routers.whoami.rule=Host(`whoami.nas.com`)"
            - "traefik.http.routers.whoami.middlewares=traefik-forward-auth@docker"

            # - "traefik.http.routers.whoami-ssl.entrypoints=https"
            # - "traefik.http.routers.whoami-ssl.tls=true"
            # - "traefik.http.routers.whoami-ssl.tls.certresolver=myresolver"
            # - "traefik.http.routers.whoami-ssl.rule=Host(`whoami.nas.com`)"
            # - "traefik.http.routers.whoami-ssl.middlewares=traefik-forward-auth@docker"

# networks:
#     traefik:
#         external: true
#     # docker_bridge:
#     #     external: true