version: '3.9'

services:
  dnsmasq:
    image: andyshinn/dnsmasq:2.78
    container_name: dnsmasq
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq.hosts:/etc/dnsmasq.hosts
      - ./dnsmasq.resolv.conf:/etc/dnsmasq.resolv.conf
    networks:
      - traefik

networks:
    traefik:
        external: true
