version: "3.9"

services:
  jd:
    image: noobx/jd:v3
    container_name: jd
    restart: always
    tty: true
    volumes:
      - ../../../custom-apps-data/jd-scripts/config:/jd/config
      - ../../../custom-apps-data/jd-scripts/log:/jd/log
      - ../../../custom-apps-data/jd-scripts/config/own:/jd/own
      - ../../../custom-apps-data/jd-scripts/config/scripts:/jd/scripts
    ports:
      - 5678:5678
    environment: 
      - ENABLE_HANGUP=true   
      - ENABLE_WEB_PANEL=true 
    network_mode: bridge
