version: "3.9"

services:
  jd:
    image: noobx/jd:v3
    container_name: jd
    restart: always
    tty: true
    volumes:
      - ./config:/jd/config
      - ./log:/jd/log
      - ./own:/jd/own
      - ./scripts:/jd/scripts
    ports:
      - 5678:5678
    environment: 
      - ENABLE_HANGUP=true   
      - ENABLE_WEB_PANEL=true 
    network_mode: bridge
