version: '3.9'

services:
  wp:
    image: ${WP_IMAGE}
    container_name: ${WP_HOST}
    restart: always
    ports:
      - "8000:80"
      - "4430:443"
    networks:
      - traefik
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_TABLE_PREFIX: ${WP_DB_PREFIX}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_LOCALE: zh_CN
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_LOGIN', false);
        define('FORCE_SSL_ADMIN', false);
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ../../../custom-apps-data/wordpress/wordpress:/var/www/html
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.frontend.rule=Host:wp.wuwb.me"
    #   - "traefik.frontend.entryPoints=https,http"

  # pma:
  #   image: ${PMA_IMAGE}
  #   restart: always
  #   networks:
  #     - traefik
  #   environment:
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASS}
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
  #     PMA_HOST: ${DB_HOST}
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.frontend.rule=Host:${PMA_DOMAIN}"

networks:
  traefik:
    external: true
