global:
  smtp_smarthost: 'smtp.sendcloud.net:2525'　
  smtp_from: '541330190@qq.com'　　
  smtp_auth_username: 'wuwb'　     
  smtp_auth_password: '202402.'　　　 　

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  email_configs:
  - to: '291276000@qq.com'　
