version: "3.0"

services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - /share/Container/custom-apps-data/memos/:/var/opt/memos
    ports:
      - 3005:5230
    networks:
      - traefik
    labels:
      - traefik.enable=false
      # - traefik.http.services.nocodb.loadbalancer.server.port=8080
      # - "traefik.http.routers.nocodb.rule=Host(`nocodb.${DOMAINNAME}`)"
      # - traefik.http.routers.nocodb.entrypoints=https
      # - com.centurylinklabs.watchtower.enable=true

networks:
  traefik:
    external: true 

